### ISSUE TITLE
Add a page on tools for parallel programming

### ISSUE THREAD

**Issue by dstansby** [UCL-ARC/python-tooling#178]

**Comment by matt-graham** [comment]
Add some recommendations of options for parallelising operations in Python and tradeoffs. Some possible options

  * `multiprocessing` - standard library module for distributing tasks across multiple processes
  * `multiprocess` - fork of `multiprocessing` which uses `dill` instead of `pickle` to allow serializing wider range of object types including nested / anonymous functions
  * `dask` - 'Dask makes it easy to scale the Python libraries that you know and love like NumPy, pandas, and scikit-learn.'
  * `numba` - [support for parallelism via `jit(parallel=True)`](https://numba.pydata.org/numba-doc/latest/user/parallel.html)
  * `Cython` - [support for OpenMP based parallelism](https://cython.readthedocs.io/en/latest/src/userguide/parallelism.html)
  * `mpi4py` - support for MPI based parallelism
  * `jax` - [support for parallelising NumPy / scientific computing like operations using functional transforms](https://jax.readthedocs.io/en/latest/jax-101/06-parallelism.html)

Could also discuss things like `asyncio` as can be used to for example asynchronously dispatch subprocesses in parallel.

**Comment by paddyroddy** [comment]
➕ for `multiprocess` over `multiprocessing`. Have found it much simpler to work with.
