### ISSUE TITLE
[TASK]: Agree on and potentially document a process for recording outcomes of off-GitHub discussions

### ISSUE THREAD

**Issue by matt-graham** [UCL-ARC/python-tooling#292]
### What needs to be done?

Following on from discussion in thread of #288. We sometimes have conversations about this project off-GitHub - for example during the semi-regular in-person hackathon events we've been running or on the internal ARC Slack workspace. To make sure those not present in these discussions are aware of the points raised and the rationale behind any decisions made, I would suggest we should have some minimal process around ensuring we sufficiently document such conversations to allow everyone the chance to contribute.

We generally already create issue corresponding to any decision about changes to be made, but sometimes these have been very barebones and not had any summary explaining why a decision was made. I would suggest we just ensure that in any such issue we give a (potentially very brief) summary of the points made in the initial issue comment. We could potentially even have an issue template specifically for this, though not entirely sure that makes sense?

**Comment by samcunliffe** [comment]
I acknowledge that #254 could have done with more text in the leading comment.

But FWIW I'm also OK with the workflow that we ended up having. It seems sane to me...

* Potentially contentious changes were explicit in the name of the issue and PR,
* comment challenging the decision on the PR was raised and PR marked as "changes requested" because changes were requested,
* ...discussion ensued.

Modulo that I disagree with [the comment here](https://github.com/UCL-ARC/python-tooling/pull/288#issuecomment-1908384300). In-person decisions are not final. Differing opinions are welcome. This is now [explicitly codified in line 21 of our CoC](https://github.com/UCL-ARC/python-tooling/blame/main/CODE_OF_CONDUCT.md#L21).

**Comment by dstansby** [comment]
>  I would suggest we just ensure that in any such issue we give a (potentially very brief) summary of the points made in the initial issue comment. 

I'm 👍 this - it makes it much more inclusive as a project if everyone can see why decisions have been taken, and I don't think it adds much more effort on top of in person discussions to jot reasons behind a decision down. Indeed, it also helps remember why a decision has been taken later - I think someone who was in person commented on a thread somewhere that they had forgotten why a decision had been made!

**Comment by samcunliffe** [comment]
# Notes from hackmorning 2024-10-22

We will write hackmorning discussion in a comment. These summaries are de-facto agreed by all attendees of the hackmorning.
We try to ensure we have a summary of the discussion and section for decision:

```md
# Notes from hackmorning 20YY-MM-DD

## Discussion

Longer section with bullet points covering main discussion points

## Summary

For people who want the gist of the discussion.

## Decisions

What are we going to do.
```
