### ISSUE TITLE
`github_user` does not indicate value can be an organisation

### ISSUE THREAD

**Issue by dstansby** [UCL-ARC/python-tooling#305]
I didn't realise that the intent of the `github_user` variable was to be the username or organisation where the git repository is remotely located. So when I ran the cookiecutter I put in my username, then had to change it all to the org I was actually using.

I think this is best solved by solving https://github.com/UCL-ARC/python-tooling/issues/296.

**Comment by samcunliffe** [comment]
I think it might be even worse: because we provide issue templates in the template's `.github` directory (and possibly other things), the `github_user` **must** be a username even though the user might want the repo owner might be an organisation.

... we're being too smart.

We could have two questions: `github_username`, `github_repo_owner` (which may be the same thing). But then that's another question.

**Comment by dstansby** [comment]
I would suggest removing the assignee from the Github issue templates? Especially for collaborative projects, I don't think it makes much sense to have a single issue assignee, and from my experience a lot of the time I work on projects that don't have a single person assigned to every issue so it would be nice not to have this as default on.

**Comment by samcunliffe** [comment]
This is not fixed via #308 although that PR solves my [comment, above](https://github.com/UCL-ARC/python-tooling/issues/305#issuecomment-1947897708).
