### ISSUE TITLE
Add codespell to pre-commit config

### ISSUE THREAD

**Issue by dstansby** [UCL-ARC/python-tooling#54]
A suggestion to add https://github.com/codespell-project/codespell. I've found it useful in the past.

**Comment by paddyroddy** [comment]
Just gave this a go. Looks good!

**Comment by samcunliffe** [comment]
It is great. And we should [recommend it](https://github.com/UCL-ARC/python-tooling) for sure.

Not convinced baking it into the pre-commit is a good idea though: I've seen false positives before. And also had it break my code. (Perfectly fine, and trivial to revert... so long as it's not required in order to merge PRs or push commits.)
