### ISSUE TITLE
tox configuration requires tox version 4

### ISSUE THREAD

**Issue by matt-graham** [UCL-ARC/python-tooling#64]
While using this template for https://github.com/UCL/dxh (thanks all for the work in getting this set up 😁) I found that the default `legacy_tox_ini` in the `[tool.tox]` section of the generated `pyproject.toml` 

https://github.com/UCL-ARC/python-template/blob/ddf6cc2f8388efa9b9b2c8873f2ea5e837247b01/%7B%7Bcookiecutter.project_slug%7D%7D/pyproject.toml#L144-L169

needed a few tweaks before I could get `tox` running locally with the version I had installed (v3.24.5)

- Removing the whitespace indentation within the `""" .... """` multiline string
- [Adding `isolated_build = true` to the `[tox]` section](https://tox.wiki/en/3.24.5/config.html#conf-isolated_build)

Might be worth documenting this and/or pinning the `tox` version in the `dev` list to `tox>=4` in `optional-dependencies` . Potentially may also be worth adding version pin when `tox` is installed in Actions workflows though not sure if it is likely that a previous version will get installed on Actions runners in practice.

**Comment by samcunliffe** [comment]
Thanks a lot for trying it out!

@paddyroddy, @p-j-smith, what do you think? I'd be up for pinning tox v4 and deleting all the legacy stuff. 
We get [tox 4.3 on the GitHub runners](https://github.com/UCL-ARC/python-template/actions/runs/5517004698/jobs/10059049784#step:4:13). And newer is... gooder?

Is there some place where v3 is kicking around? (my 🍎 `brew` and `pip` both give me 4.6).

**Comment by p-j-smith** [comment]
>  I'd be up for pinning tox v4 and deleting all the legacy stuff.

yeah definitely, newer is much gooder. tox v4 requires `Python>=3.7`, but I think that's fine?

**Comment by matt-graham** [comment]
> Is there some place where v3 is kicking around? (my 🍎 `brew` and `pip` both give me 4.6).

Good question. I'm not sure why the local `conda` environment I was using picked the older version it did (v3.27.1), but guessing one of the upstream dependencies when I created environment was pinning `tox<4` [as v3.27.1 seems to be the latest v3.x release for which a `conda-forge` package is available](https://anaconda.org/conda-forge/tox/files), though `conda` happily updated to v4.6.4 in the same environment when I noticed the above issue so doesn't seem to be anything restricting now. Don't know of any good reasons for not using tox v4 so seems safe to pin, and at least this would give a loud error when trying to resolve dependencies if another package is restricting the tox version.

**Comment by paddyroddy** [comment]
Some thoughts:
- `tox==4.0.0` came out on 07/12/2022. I hadn't considered that people might even be using earlier versions. Makes sense to pin (I try to refrain from pinning too much). Personally, I don't think we should be supporting `<4`.
- The `legacy_tox_ini` sounds like its legacy, but it is because `pyproject.toml` doesn't fully support `toml` for `tox`. See here why we do it this way https://tox.wiki/en/4.6.4/config.html#pyproject-toml
- IMO we don't need to pin the actions. I guess we could, but then what happens when `5` is released and we forget we've pinned it.

I'll raise a PR to fix this - which is just by pinning in `pyproject.toml`. Thanks for spotting @matt-graham!
